import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:900}});const errors=[];page.on('pageerror',error=>errors.push(error.message));
const base=process.env.COMMUNITY_TEST_URL||'http://127.0.0.1:4198';
const wait=async(text)=>page.getByText(text,{exact:true}).first().waitFor();
const role=async(value)=>{await page.getByLabel('Test persona').selectOption(value);await page.getByText(`Fictional ${value==='moderator'?'moderator':'member'}: ${value} · camden town`,{exact:true}).waitFor();await page.getByText('Loading community records...').waitFor({state:'hidden'});};
const choose=async(name)=>page.getByRole('navigation',{name:'Community sections'}).getByRole('button',{name,exact:true}).click();
const openRecord=async()=>page.locator('.cw-record-list button').first().click();
try{
 await page.goto(base);await choose('Share observation');
 await page.getByLabel('Short title',{exact:true}).fill('Fictional accessible path observation');await page.getByLabel('Approximate public place').fill('Camden station approach');await page.getByLabel('Publication preference').selectOption('reviewed_public');
 await page.getByRole('button',{name:'Review observation',exact:true}).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Back to fields',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.getByLabel('Short title',{exact:true}).inputValue(),'Fictional accessible path observation');
 await page.getByRole('button',{name:'Review observation',exact:true}).click();await page.getByRole('button',{name:'Confirm private submission',exact:true}).click();await page.getByRole('region',{name:'Private report receipt'}).waitFor();assert.match(await page.locator('.cw-detail').innerText(),/submitted · revision 1/);
 await role('sam');assert.equal(await page.locator('.cw-record-list button').count(),0);
 await role('moderator');await openRecord();await page.getByLabel('Review decision').selectOption('clarify');await page.getByLabel('Private review reason',{exact:true}).fill('Please clarify the approximate public location.');await page.getByRole('button',{name:'Save review decision',exact:true}).click();await wait('needs clarification · revision 2');
 await role('alex');await openRecord();await page.getByLabel('Clarification response',{exact:true}).fill('The observation concerns the broad station approach.');await page.getByRole('button',{name:'Send private clarification',exact:true}).click();await wait('submitted · revision 3');
 await role('moderator');await openRecord();await page.getByLabel('Review decision').selectOption('approve');await page.getByLabel('Private review reason',{exact:true}).fill('Fictional content reviewed for a redacted summary.');await page.getByLabel('Public-safe summary',{exact:true}).fill('A fictional contributor describes a path access concern. Current conditions remain unconfirmed.');await page.getByRole('button',{name:'Save review decision',exact:true}).click();await wait('published · revision 4');
 await role('sam');await choose('Reviewed updates');await page.getByLabel('Add a fictional update',{exact:true}).fill('Fictional follow-up about access at the broad station approach.');await page.getByRole('button',{name:'Submit update for review',exact:true}).click();await wait('Update saved privately for moderation.');assert.equal(await page.locator('.cw-public').getByText('Fictional follow-up about access at the broad station approach.',{exact:true}).count(),0);
 await role('moderator');await choose('Discussion queue');await page.getByLabel('Private discussion reason').fill('Private narrative reduced to an anonymous summary.');await page.getByLabel('Redacted public update').fill('A fictional follow-up describes access in the broad area.');await page.getByRole('button',{name:'Save discussion review',exact:true}).click();await page.getByText('approved',{exact:true}).waitFor();
 await role('alex');await choose('Reviewed updates');await page.getByRole('button',{name:'Prepare current notice link',exact:true}).click();const link=await page.getByRole('link',{name:'Open current notice link',exact:true}).getAttribute('href');assert.ok(link.includes('notice='));assert.ok(!link.includes('narrative'));await page.getByText(/A fictional follow-up describes access in the broad area/).waitFor();
 for(const width of[320,390,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));}
 await choose('My reports');await openRecord();await page.getByRole('button',{name:'Correct observation',exact:true}).click();await page.getByLabel('Short title',{exact:true}).fill('Fictional corrected path observation');await page.getByRole('button',{name:'Review observation',exact:true}).click();await page.getByRole('button',{name:'Confirm private submission',exact:true}).click();await wait('correction pending · revision 5');await choose('Reviewed updates');await wait('No current reviewed community updates. This does not confirm that conditions are clear.');
 await page.goto(base+link);await wait('This shared notice is no longer available. Removed summaries are not displayed.');assert.equal(await page.locator('.cw-public').count(),0);
 await choose('My reports');await openRecord();await page.getByRole('button',{name:'Withdraw observation',exact:true}).click();await wait('withdrawn · revision 6');assert.ok(!(await page.locator('.cw-detail').innerText()).includes('The observation concerns the broad station approach.'));
 await mkdir('.data/community-workflow',{recursive:true});for(const width of[320,390,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:`.data/community-workflow/receipt-${width}.png`,fullPage:true});}
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:['structured intake with keyboard review and retained draft','owner isolation','clarification and publication','moderated discussion','deliberate current link','post-publication correction hides old projection','stale links fail closed','withdrawal scrubs private narrative','320/390/1440 layout','no browser errors']}));
}finally{await browser.close();}
